class ScoreClassification:
    ACCURACY = 'accuracy'
    F1 = 'f1'
    F1_WEIGHTED = 'f1_weighted'
    F1_MACRO = 'f1_macro'
    F1_MICRO = 'f1_micro'
    PRECISION = 'precision'
    PRECISION_WEIGHTED = 'precision_weighted'
    PRECISION_MACRO = 'precision_macro'
    PRECISION_MICRO = 'precision_micro'
    RECALL = 'recall'
    RECALL_WEIGHTED = 'recall_weighted'
    RECALL_MACRO = 'recall_macro'
    RECALL_MICRO = 'recall_micro'
    ROC_AUC = 'roc_auc'
    ROC_AUC_WEIGHTED = 'roc_auc_weighted'
    ROC_AUC_MACRO = 'roc_auc_macro'
    ROC_AUC_MICRO = 'roc_auc_micro'